/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module \$paramod$c5d5f6af8907815d9d88b76936d70ac1e6314167\RXTOP (clk, rst, parEnable, parityType, rx_in, bclk, rx_out, pCheckError, pCheckValid, busy, rx_done, framingError);
  input bclk;
  wire bclk;
  output busy;
  wire busy;
  input clk;
  wire clk;
  wire deSerializerDn_wire;
  output framingError;
  wire framingError;
  wire fsm_deSerializerEn_wire;
  wire fsm_parity_check_en_wire;
  output pCheckError;
  wire pCheckError;
  output pCheckValid;
  wire pCheckValid;
  input parEnable;
  wire parEnable;
  input parityType;
  wire parityType;
  input rst;
  wire rst;
  output rx_done;
  wire rx_done;
  input rx_in;
  wire rx_in;
  output [7:0] rx_out;
  wire [7:0] rx_out;
  \$paramod\Deserializer\DATAWIDTH=s32'00000000000000000000000000001000  deserializer (
    .clk(clk),
    .dataIn(rx_in),
    .dataOut(rx_out),
    .deSerializerDn(deSerializerDn_wire),
    .deSerializerEn(fsm_deSerializerEn_wire),
    .done(rx_done),
    .rst(rst)
  );
  \$paramod\FSMRX\OVERSAMPLING=s32'00000000000000000000000000010000  fsm_rx (
    .baud(bclk),
    .busy(busy),
    .clk(clk),
    .dataIn(rx_in),
    .deSerializerDn(deSerializerDn_wire),
    .deSerializerEn(fsm_deSerializerEn_wire),
    .done(rx_done),
    .framingError(framingError),
    .parEn(parEnable),
    .parityCheckEn(fsm_parity_check_en_wire),
    .rst(rst)
  );
  \$paramod\ParityCheck\DATAWIDTH=s32'00000000000000000000000000001000  pCheck (
    .clk(clk),
    .deSerIn(rx_out),
    .deSerializerDn(deSerializerDn_wire),
    .done(rx_done),
    .error(pCheckError),
    .parityCheckEn(fsm_parity_check_en_wire),
    .parityType(parityType),
    .rst(rst),
    .serIn(rx_in),
    .valid(pCheckValid)
  );
endmodule

module \$paramod$c5d5f6af8907815d9d88b76936d70ac1e6314167\TXTOP (clk, rst, parEnable, dataValid, parityType, dataInput, bclk, tx_out, busy, tx_done);
  wire SerializerDn_wire;
  input bclk;
  wire bclk;
  output busy;
  wire busy;
  input clk;
  wire clk;
  input [7:0] dataInput;
  wire [7:0] dataInput;
  input dataValid;
  wire dataValid;
  wire data_mux_wire;
  wire [2:0] muxSelector_wire;
  input parEnable;
  wire parEnable;
  input parityType;
  wire parityType;
  wire parity_mux_wire;
  input rst;
  wire rst;
  wire serializerEn_wire;
  output tx_done;
  wire tx_done;
  output tx_out;
  wire tx_out;
  \$paramod\FSMTX\OVERSAMPLING=s32'00000000000000000000000000010000  fsm_tx (
    .SerializerDn(SerializerDn_wire),
    .baud(bclk),
    .busy(busy),
    .clk(clk),
    .dataValid(dataValid),
    .done(tx_done),
    .muxSelector(muxSelector_wire),
    .parEn(parEnable),
    .rst(rst),
    .serializerEn(serializerEn_wire)
  );
  MUX mux (
    .data(data_mux_wire),
    .idle(1'h1),
    .parity(parity_mux_wire),
    .selector(muxSelector_wire),
    .start(1'h0),
    .stop(1'h1),
    .tx_out(tx_out)
  );
  \$paramod\ParityCalculator\DATAWIDTH=s32'00000000000000000000000000001000  pCalc (
    .clk(clk),
    .dataIn(dataInput),
    .dataValid(dataValid),
    .parityBit(parity_mux_wire),
    .parityType(parityType),
    .rst(rst)
  );
  \$paramod\Serializer\DATAWIDTH=s32'00000000000000000000000000001000  serializer (
    .SerializerDn(SerializerDn_wire),
    .clk(clk),
    .dataIn(dataInput),
    .dataOut(data_mux_wire),
    .dataValid(dataValid),
    .rst(rst),
    .serializerEn(serializerEn_wire)
  );
endmodule

module \$paramod\Deserializer\DATAWIDTH=s32'00000000000000000000000000001000 (clk, rst, deSerializerEn, dataIn, done, deSerializerDn, dataOut);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input clk;
  wire clk;
  input dataIn;
  wire dataIn;
  output [7:0] dataOut;
  wire [7:0] dataOut;
  output deSerializerDn;
  wire deSerializerDn;
  input deSerializerEn;
  wire deSerializerEn;
  input done;
  wire done;
  wire [3:0] ptr;
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _20_ (
    .A(done),
    .B(deSerializerEn),
    .Y(_12_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _21_ (
    .A(deSerializerEn),
    .SLEEP(done),
    .X(_13_)
  );
  sky130_fd_sc_hd__a22o_1 _22_ (
    .A1(dataOut[0]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[1]),
    .X(_00_)
  );
  sky130_fd_sc_hd__a22o_1 _23_ (
    .A1(dataOut[1]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[2]),
    .X(_01_)
  );
  sky130_fd_sc_hd__a22o_1 _24_ (
    .A1(dataOut[2]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[3]),
    .X(_02_)
  );
  sky130_fd_sc_hd__a22o_1 _25_ (
    .A1(dataOut[3]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[4]),
    .X(_03_)
  );
  sky130_fd_sc_hd__a22o_1 _26_ (
    .A1(dataOut[4]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[5]),
    .X(_04_)
  );
  sky130_fd_sc_hd__a22o_1 _27_ (
    .A1(dataOut[5]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[6]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a22o_1 _28_ (
    .A1(dataOut[6]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataOut[7]),
    .X(_06_)
  );
  sky130_fd_sc_hd__a22o_1 _29_ (
    .A1(dataOut[7]),
    .A2(_12_),
    .B1(_13_),
    .B2(dataIn),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(_13_),
    .A1(_12_),
    .S(ptr[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _31_ (
    .A(ptr[0]),
    .B(ptr[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _32_ (
    .A(ptr[0]),
    .SLEEP(ptr[1]),
    .X(_15_)
  );
  sky130_fd_sc_hd__a32o_1 _33_ (
    .A1(_13_),
    .A2(_14_),
    .A3(_15_),
    .B1(_12_),
    .B2(ptr[1]),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand4_1 _34_ (
    .A(ptr[0]),
    .B(ptr[1]),
    .C(ptr[2]),
    .D(deSerializerEn),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a31oi_1 _35_ (
    .A1(ptr[0]),
    .A2(ptr[1]),
    .A3(deSerializerEn),
    .B1(ptr[2]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(done),
    .B(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and2_0 _37_ (
    .A(_16_),
    .B(_18_),
    .X(_10_)
  );
  sky130_fd_sc_hd__xor2_1 _38_ (
    .A(ptr[3]),
    .B(_16_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nor2_1 _39_ (
    .A(done),
    .B(_19_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3b_1 _40_ (
    .A(_15_),
    .B(ptr[2]),
    .C_N(ptr[3]),
    .Y(deSerializerDn)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(clk),
    .D(_00_),
    .Q(dataOut[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(clk),
    .D(_01_),
    .Q(dataOut[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(clk),
    .D(_02_),
    .Q(dataOut[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(_03_),
    .Q(dataOut[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(_04_),
    .Q(dataOut[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_05_),
    .Q(dataOut[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_06_),
    .Q(dataOut[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_07_),
    .Q(dataOut[7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_08_),
    .Q(ptr[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_09_),
    .Q(ptr[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_10_),
    .Q(ptr[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_11_),
    .Q(ptr[3]),
    .RESET_B(rst)
  );
endmodule

module \$paramod\FSMRX\OVERSAMPLING=s32'00000000000000000000000000010000 (baud, deSerializerDn, parEn, clk, rst, dataIn, deSerializerEn, done, parityCheckEn, busy, framingError);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire [4:0] BAUD_COUNTER;
  wire [4:0] BAUD_COUNTER_Next;
  wire [2:0] Current;
  input baud;
  wire baud;
  output busy;
  wire busy;
  input clk;
  wire clk;
  input dataIn;
  wire dataIn;
  input deSerializerDn;
  wire deSerializerDn;
  output deSerializerEn;
  wire deSerializerEn;
  output done;
  wire done;
  output framingError;
  wire framingError;
  input parEn;
  wire parEn;
  output parityCheckEn;
  wire parityCheckEn;
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _41_ (
    .A(BAUD_COUNTER[0]),
    .B(BAUD_COUNTER[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(BAUD_COUNTER[2]),
    .B(BAUD_COUNTER[3]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and3_1 _43_ (
    .A(BAUD_COUNTER[4]),
    .B(_03_),
    .C(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand3_1 _44_ (
    .A(BAUD_COUNTER[4]),
    .B(_03_),
    .C(_04_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _45_ (
    .A(Current[0]),
    .SLEEP(Current[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(Current[1]),
    .B(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _47_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor3b_1 _48_ (
    .A(BAUD_COUNTER[2]),
    .B(BAUD_COUNTER[4]),
    .C_N(BAUD_COUNTER[3]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _49_ (
    .A(_07_),
    .SLEEP(Current[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__a21boi_0 _50_ (
    .A1(_03_),
    .A2(_10_),
    .B1_N(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _51_ (
    .A(Current[0]),
    .B(Current[1]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor3b_1 _52_ (
    .A(Current[0]),
    .B(Current[2]),
    .C_N(Current[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _53_ (
    .A(deSerializerDn),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand3_1 _54_ (
    .A(deSerializerDn),
    .B(parEn),
    .C(_14_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__o41ai_1 _55_ (
    .A1(Current[0]),
    .A2(Current[1]),
    .A3(Current[2]),
    .A4(dataIn),
    .B1(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__or3_1 _56_ (
    .A(_09_),
    .B(_12_),
    .C(_17_),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _57_ (
    .A(Current[2]),
    .B(_13_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand3b_1 _58_ (
    .A_N(Current[2]),
    .B(dataIn),
    .C(_13_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _59_ (
    .A(_14_),
    .SLEEP(deSerializerDn),
    .X(_20_)
  );
  sky130_fd_sc_hd__nand2b_1 _60_ (
    .A_N(deSerializerDn),
    .B(_14_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor2_1 _61_ (
    .A(_05_),
    .B(_21_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__o21ai_0 _62_ (
    .A1(_05_),
    .A2(_18_),
    .B1(_19_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o41ai_1 _63_ (
    .A1(_09_),
    .A2(_12_),
    .A3(_22_),
    .A4(_23_),
    .B1(Current[1]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand3_1 _64_ (
    .A(_03_),
    .B(_10_),
    .C(_11_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nor2_1 _65_ (
    .A(_06_),
    .B(_21_),
    .Y(deSerializerEn)
  );
  sky130_fd_sc_hd__o2111ai_1 _66_ (
    .A1(_06_),
    .A2(_21_),
    .B1(_24_),
    .C1(_25_),
    .D1(_16_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _67_ (
    .A(_06_),
    .B(_08_),
    .Y(parityCheckEn)
  );
  sky130_fd_sc_hd__a31oi_1 _68_ (
    .A1(Current[2]),
    .A2(_06_),
    .A3(_13_),
    .B1(parityCheckEn),
    .Y(_26_)
  );
  sky130_fd_sc_hd__o21ai_0 _69_ (
    .A1(parEn),
    .A2(_15_),
    .B1(_26_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _70_ (
    .A(_08_),
    .B(_18_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__or3_1 _71_ (
    .A(_11_),
    .B(_14_),
    .C(_27_),
    .X(busy)
  );
  sky130_fd_sc_hd__nor2_1 _72_ (
    .A(_06_),
    .B(_18_),
    .Y(done)
  );
  sky130_fd_sc_hd__nor3_1 _73_ (
    .A(dataIn),
    .B(_06_),
    .C(_18_),
    .Y(framingError)
  );
  sky130_fd_sc_hd__nor3_1 _74_ (
    .A(_07_),
    .B(_13_),
    .C(_14_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a2111oi_0 _75_ (
    .A1(_06_),
    .A2(_27_),
    .B1(_28_),
    .C1(_12_),
    .D1(_22_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__xnor2_1 _76_ (
    .A(BAUD_COUNTER[0]),
    .B(baud),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nor2_1 _77_ (
    .A(_29_),
    .B(_30_),
    .Y(BAUD_COUNTER_Next[0])
  );
  sky130_fd_sc_hd__nor3_1 _78_ (
    .A(Current[0]),
    .B(Current[2]),
    .C(_20_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a21oi_1 _79_ (
    .A1(BAUD_COUNTER[0]),
    .A2(baud),
    .B1(BAUD_COUNTER[1]),
    .Y(_32_)
  );
  sky130_fd_sc_hd__and3_1 _80_ (
    .A(BAUD_COUNTER[0]),
    .B(BAUD_COUNTER[1]),
    .C(baud),
    .X(_33_)
  );
  sky130_fd_sc_hd__nor3_1 _81_ (
    .A(_31_),
    .B(_32_),
    .C(_33_),
    .Y(BAUD_COUNTER_Next[1])
  );
  sky130_fd_sc_hd__nor2_1 _82_ (
    .A(BAUD_COUNTER[2]),
    .B(_33_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__and2_0 _83_ (
    .A(BAUD_COUNTER[2]),
    .B(_33_),
    .X(_35_)
  );
  sky130_fd_sc_hd__nor3_1 _84_ (
    .A(_31_),
    .B(_34_),
    .C(_35_),
    .Y(BAUD_COUNTER_Next[2])
  );
  sky130_fd_sc_hd__nor4_1 _85_ (
    .A(_12_),
    .B(_20_),
    .C(_27_),
    .D(_28_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nand2_1 _86_ (
    .A(BAUD_COUNTER[3]),
    .B(_35_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__xnor2_1 _87_ (
    .A(BAUD_COUNTER[3]),
    .B(_35_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nor2_1 _88_ (
    .A(_36_),
    .B(_38_),
    .Y(BAUD_COUNTER_Next[3])
  );
  sky130_fd_sc_hd__a2111oi_0 _89_ (
    .A1(_06_),
    .A2(_27_),
    .B1(_28_),
    .C1(_11_),
    .D1(_22_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__xor2_1 _90_ (
    .A(BAUD_COUNTER[4]),
    .B(_37_),
    .X(_40_)
  );
  sky130_fd_sc_hd__nor2_1 _91_ (
    .A(_39_),
    .B(_40_),
    .Y(BAUD_COUNTER_Next[4])
  );
  sky130_fd_sc_hd__dfrtp_1 _92_ (
    .CLK(clk),
    .D(_00_),
    .Q(Current[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _93_ (
    .CLK(clk),
    .D(_01_),
    .Q(Current[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _94_ (
    .CLK(clk),
    .D(_02_),
    .Q(Current[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _95_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[0]),
    .Q(BAUD_COUNTER[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _96_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[1]),
    .Q(BAUD_COUNTER[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _97_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[2]),
    .Q(BAUD_COUNTER[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _98_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[3]),
    .Q(BAUD_COUNTER[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _99_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[4]),
    .Q(BAUD_COUNTER[4]),
    .RESET_B(rst)
  );
endmodule

module \$paramod\FSMTX\OVERSAMPLING=s32'00000000000000000000000000010000 (baud, SerializerDn, parEn, clk, rst, dataValid, muxSelector, serializerEn, busy, done);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire [4:0] BAUD_COUNTER;
  wire [4:0] BAUD_COUNTER_Next;
  wire [2:0] Current;
  input SerializerDn;
  wire SerializerDn;
  input baud;
  wire baud;
  output busy;
  wire busy;
  input clk;
  wire clk;
  input dataValid;
  wire dataValid;
  output done;
  wire done;
  output [2:0] muxSelector;
  wire [2:0] muxSelector;
  input parEn;
  wire parEn;
  input rst;
  wire rst;
  output serializerEn;
  wire serializerEn;
  sky130_fd_sc_hd__clkinv_1 _33_ (
    .A(Current[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _34_ (
    .A(Current[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _35_ (
    .A(parEn),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2b_1 _36_ (
    .A_N(BAUD_COUNTER[0]),
    .B(BAUD_COUNTER[4]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__or3_1 _37_ (
    .A(BAUD_COUNTER[1]),
    .B(BAUD_COUNTER[2]),
    .C(BAUD_COUNTER[3]),
    .X(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _38_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _39_ (
    .A(_06_),
    .SLEEP(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(Current[0]),
    .B(Current[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__or3b_1 _41_ (
    .A(Current[0]),
    .B(Current[2]),
    .C_N(Current[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__nand2b_1 _42_ (
    .A_N(Current[2]),
    .B(Current[0]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__or3b_1 _43_ (
    .A(Current[0]),
    .B(Current[1]),
    .C_N(Current[2]),
    .X(_13_)
  );
  sky130_fd_sc_hd__nand3_1 _44_ (
    .A(_11_),
    .B(_12_),
    .C(_13_),
    .Y(busy)
  );
  sky130_fd_sc_hd__nor3_1 _45_ (
    .A(Current[0]),
    .B(Current[1]),
    .C(Current[2]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__or3_1 _46_ (
    .A(Current[0]),
    .B(Current[1]),
    .C(Current[2]),
    .X(_15_)
  );
  sky130_fd_sc_hd__nor2_1 _47_ (
    .A(dataValid),
    .B(_15_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor4_1 _48_ (
    .A(SerializerDn),
    .B(_06_),
    .C(_07_),
    .D(_11_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a211oi_1 _49_ (
    .A1(_09_),
    .A2(busy),
    .B1(_16_),
    .C1(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand3_1 _50_ (
    .A(Current[1]),
    .B(SerializerDn),
    .C(_10_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__or3_1 _51_ (
    .A(_05_),
    .B(_09_),
    .C(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__nand2_1 _52_ (
    .A(dataValid),
    .B(_14_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o211ai_1 _53_ (
    .A1(_03_),
    .A2(_18_),
    .B1(_20_),
    .C1(_21_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__or3_1 _54_ (
    .A(Current[1]),
    .B(_09_),
    .C(_12_),
    .X(_22_)
  );
  sky130_fd_sc_hd__o211ai_1 _55_ (
    .A1(_04_),
    .A2(_18_),
    .B1(_20_),
    .C1(_22_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__o221a_1 _56_ (
    .A1(_04_),
    .A2(_12_),
    .B1(_19_),
    .B2(parEn),
    .C1(_08_),
    .X(_23_)
  );
  sky130_fd_sc_hd__a21oi_1 _57_ (
    .A1(_09_),
    .A2(_13_),
    .B1(_23_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _58_ (
    .A(_09_),
    .B(_13_),
    .Y(done)
  );
  sky130_fd_sc_hd__mux2i_1 _59_ (
    .A0(_15_),
    .A1(_09_),
    .S(busy),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _60_ (
    .A(BAUD_COUNTER[0]),
    .B(baud),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nor2_1 _61_ (
    .A(_24_),
    .B(_25_),
    .Y(BAUD_COUNTER_Next[0])
  );
  sky130_fd_sc_hd__and3_1 _62_ (
    .A(BAUD_COUNTER[0]),
    .B(BAUD_COUNTER[1]),
    .C(baud),
    .X(_26_)
  );
  sky130_fd_sc_hd__a21oi_1 _63_ (
    .A1(BAUD_COUNTER[0]),
    .A2(baud),
    .B1(BAUD_COUNTER[1]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor3_1 _64_ (
    .A(_14_),
    .B(_26_),
    .C(_27_),
    .Y(BAUD_COUNTER_Next[1])
  );
  sky130_fd_sc_hd__and4_1 _65_ (
    .A(BAUD_COUNTER[0]),
    .B(BAUD_COUNTER[1]),
    .C(BAUD_COUNTER[2]),
    .D(baud),
    .X(_28_)
  );
  sky130_fd_sc_hd__o21ai_0 _66_ (
    .A1(BAUD_COUNTER[2]),
    .A2(_26_),
    .B1(_15_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor2_1 _67_ (
    .A(_28_),
    .B(_29_),
    .Y(BAUD_COUNTER_Next[2])
  );
  sky130_fd_sc_hd__nand2_1 _68_ (
    .A(BAUD_COUNTER[3]),
    .B(_28_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__o21ai_0 _69_ (
    .A1(BAUD_COUNTER[3]),
    .A2(_28_),
    .B1(_15_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a21oi_1 _70_ (
    .A1(BAUD_COUNTER[3]),
    .A2(_28_),
    .B1(_31_),
    .Y(BAUD_COUNTER_Next[3])
  );
  sky130_fd_sc_hd__xor2_1 _71_ (
    .A(BAUD_COUNTER[4]),
    .B(_30_),
    .X(_32_)
  );
  sky130_fd_sc_hd__nor2_1 _72_ (
    .A(_24_),
    .B(_32_),
    .Y(BAUD_COUNTER_Next[4])
  );
  sky130_fd_sc_hd__nand2b_1 _73_ (
    .A_N(_17_),
    .B(_22_),
    .Y(serializerEn)
  );
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(clk),
    .D(_00_),
    .Q(Current[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _75_ (
    .CLK(clk),
    .D(_01_),
    .Q(Current[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _76_ (
    .CLK(clk),
    .D(_02_),
    .Q(Current[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _77_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[0]),
    .Q(BAUD_COUNTER[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _78_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[1]),
    .Q(BAUD_COUNTER[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _79_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[2]),
    .Q(BAUD_COUNTER[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _80_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[3]),
    .Q(BAUD_COUNTER[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _81_ (
    .CLK(clk),
    .D(BAUD_COUNTER_Next[4]),
    .Q(BAUD_COUNTER[4]),
    .RESET_B(rst)
  );
  assign muxSelector = Current;
endmodule

module \$paramod\ParityCalculator\DATAWIDTH=s32'00000000000000000000000000001000 (clk, rst, dataValid, parityType, dataIn, parityBit);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clk;
  wire clk;
  input [7:0] dataIn;
  wire [7:0] dataIn;
  input dataValid;
  wire dataValid;
  wire [7:0] memory;
  output parityBit;
  wire parityBit;
  input parityType;
  wire parityType;
  input rst;
  wire rst;
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(memory[0]),
    .A1(dataIn[0]),
    .S(dataValid),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(memory[1]),
    .A1(dataIn[1]),
    .S(dataValid),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(memory[2]),
    .A1(dataIn[2]),
    .S(dataValid),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(memory[3]),
    .A1(dataIn[3]),
    .S(dataValid),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(memory[4]),
    .A1(dataIn[4]),
    .S(dataValid),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(memory[5]),
    .A1(dataIn[5]),
    .S(dataValid),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(memory[6]),
    .A1(dataIn[6]),
    .S(dataValid),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(memory[7]),
    .A1(dataIn[7]),
    .S(dataValid),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _22_ (
    .A(memory[0]),
    .B(memory[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(memory[2]),
    .B(memory[3]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _24_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(memory[4]),
    .B(memory[5]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(memory[6]),
    .B(memory[7]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor3_1 _28_ (
    .A(parityType),
    .B(_10_),
    .C(_13_),
    .X(parityBit)
  );
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(clk),
    .D(_00_),
    .Q(memory[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(clk),
    .D(_01_),
    .Q(memory[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _31_ (
    .CLK(clk),
    .D(_02_),
    .Q(memory[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clk),
    .D(_03_),
    .Q(memory[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(_04_),
    .Q(memory[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(_05_),
    .Q(memory[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(_06_),
    .Q(memory[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(_07_),
    .Q(memory[7]),
    .RESET_B(rst)
  );
endmodule

module \$paramod\ParityCheck\DATAWIDTH=s32'00000000000000000000000000001000 (clk, rst, done, deSerializerDn, parityType, parityCheckEn, serIn, deSerIn, error, valid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input clk;
  wire clk;
  input [7:0] deSerIn;
  wire [7:0] deSerIn;
  input deSerializerDn;
  wire deSerializerDn;
  input done;
  wire done;
  output error;
  wire error;
  wire [7:0] memory;
  wire parityBit;
  input parityCheckEn;
  wire parityCheckEn;
  input parityType;
  wire parityType;
  input rst;
  wire rst;
  input serIn;
  wire serIn;
  output valid;
  wire valid;
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(parityCheckEn),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o21ai_0 _24_ (
    .A1(done),
    .A2(_10_),
    .B1(error),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(memory[0]),
    .B(memory[1]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(memory[2]),
    .B(memory[3]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(memory[4]),
    .B(memory[5]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(memory[6]),
    .B(memory[7]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xnor3_1 _31_ (
    .A(serIn),
    .B(_14_),
    .C(_17_),
    .X(_18_)
  );
  sky130_fd_sc_hd__xor2_1 _32_ (
    .A(parityType),
    .B(_18_),
    .X(_19_)
  );
  sky130_fd_sc_hd__o31ai_1 _33_ (
    .A1(done),
    .A2(_10_),
    .A3(_19_),
    .B1(_11_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(valid),
    .B(parityCheckEn),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(done),
    .B(_20_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(done),
    .B(deSerializerDn),
    .Y(_21_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _37_ (
    .A(deSerializerDn),
    .SLEEP(done),
    .X(_22_)
  );
  sky130_fd_sc_hd__a22o_1 _38_ (
    .A1(memory[0]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[0]),
    .X(_02_)
  );
  sky130_fd_sc_hd__a22o_1 _39_ (
    .A1(memory[1]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[1]),
    .X(_03_)
  );
  sky130_fd_sc_hd__a22o_1 _40_ (
    .A1(memory[2]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[2]),
    .X(_04_)
  );
  sky130_fd_sc_hd__a22o_1 _41_ (
    .A1(memory[3]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[3]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a22o_1 _42_ (
    .A1(memory[4]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[4]),
    .X(_06_)
  );
  sky130_fd_sc_hd__a22o_1 _43_ (
    .A1(memory[5]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[5]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a22o_1 _44_ (
    .A1(memory[6]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[6]),
    .X(_08_)
  );
  sky130_fd_sc_hd__a22o_1 _45_ (
    .A1(memory[7]),
    .A2(_21_),
    .B1(_22_),
    .B2(deSerIn[7]),
    .X(_09_)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_00_),
    .Q(error),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_01_),
    .Q(valid),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_02_),
    .Q(memory[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_03_),
    .Q(memory[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_04_),
    .Q(memory[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_05_),
    .Q(memory[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_06_),
    .Q(memory[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(clk),
    .D(_07_),
    .Q(memory[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _54_ (
    .CLK(clk),
    .D(_08_),
    .Q(memory[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _55_ (
    .CLK(clk),
    .D(_09_),
    .Q(memory[7]),
    .RESET_B(rst)
  );
  assign parityBit = serIn;
endmodule

module \$paramod\Serializer\DATAWIDTH=s32'00000000000000000000000000001000 (clk, rst, dataValid, serializerEn, dataIn, dataOut, SerializerDn);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  output SerializerDn;
  wire SerializerDn;
  input clk;
  wire clk;
  input [7:0] dataIn;
  wire [7:0] dataIn;
  output dataOut;
  wire dataOut;
  input dataValid;
  wire dataValid;
  wire [7:0] memory;
  wire [3:0] ptr;
  input rst;
  wire rst;
  input serializerEn;
  wire serializerEn;
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(dataValid),
    .B(serializerEn),
    .Y(_13_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _30_ (
    .A(serializerEn),
    .SLEEP(dataValid),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(_14_),
    .A1(_13_),
    .S(ptr[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _32_ (
    .A(ptr[0]),
    .B(ptr[1]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _33_ (
    .A(ptr[0]),
    .SLEEP(ptr[1]),
    .X(_16_)
  );
  sky130_fd_sc_hd__a32o_1 _34_ (
    .A1(_14_),
    .A2(_15_),
    .A3(_16_),
    .B1(_13_),
    .B2(ptr[1]),
    .X(_01_)
  );
  sky130_fd_sc_hd__a21oi_1 _35_ (
    .A1(ptr[0]),
    .A2(ptr[1]),
    .B1(ptr[2]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand3_1 _36_ (
    .A(ptr[0]),
    .B(ptr[1]),
    .C(ptr[2]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a22oi_1 _37_ (
    .A1(ptr[2]),
    .A2(_13_),
    .B1(_14_),
    .B2(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor2_1 _38_ (
    .A(_17_),
    .B(_19_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__and4_1 _39_ (
    .A(ptr[0]),
    .B(ptr[1]),
    .C(ptr[2]),
    .D(serializerEn),
    .X(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _40_ (
    .A1(ptr[3]),
    .A2(_20_),
    .B1(dataValid),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o21a_1 _41_ (
    .A1(ptr[3]),
    .A2(_20_),
    .B1(_21_),
    .X(_03_)
  );
  sky130_fd_sc_hd__a222oi_1 _42_ (
    .A1(memory[0]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[1]),
    .C1(dataValid),
    .C2(dataIn[0]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__clkinv_1 _43_ (
    .A(_22_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a222oi_1 _44_ (
    .A1(memory[1]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[2]),
    .C1(dataValid),
    .C2(dataIn[1]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__clkinv_1 _45_ (
    .A(_23_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a222oi_1 _46_ (
    .A1(memory[2]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[3]),
    .C1(dataValid),
    .C2(dataIn[2]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__clkinv_1 _47_ (
    .A(_24_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a222oi_1 _48_ (
    .A1(memory[3]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[4]),
    .C1(dataValid),
    .C2(dataIn[3]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__clkinv_1 _49_ (
    .A(_25_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a222oi_1 _50_ (
    .A1(memory[4]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[5]),
    .C1(dataValid),
    .C2(dataIn[4]),
    .Y(_26_)
  );
  sky130_fd_sc_hd__clkinv_1 _51_ (
    .A(_26_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a222oi_1 _52_ (
    .A1(memory[5]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[6]),
    .C1(dataValid),
    .C2(dataIn[5]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__clkinv_1 _53_ (
    .A(_27_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a222oi_1 _54_ (
    .A1(memory[6]),
    .A2(_13_),
    .B1(_14_),
    .B2(memory[7]),
    .C1(dataValid),
    .C2(dataIn[6]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__clkinv_1 _55_ (
    .A(_28_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a22o_1 _56_ (
    .A1(dataValid),
    .A2(dataIn[7]),
    .B1(_13_),
    .B2(memory[7]),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _57_ (
    .A0(dataOut),
    .A1(memory[0]),
    .S(_14_),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor3b_1 _58_ (
    .A(_16_),
    .B(ptr[2]),
    .C_N(ptr[3]),
    .Y(SerializerDn)
  );
  sky130_fd_sc_hd__dfrtp_1 _59_ (
    .CLK(clk),
    .D(_00_),
    .Q(ptr[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _60_ (
    .CLK(clk),
    .D(_01_),
    .Q(ptr[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _61_ (
    .CLK(clk),
    .D(_02_),
    .Q(ptr[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _62_ (
    .CLK(clk),
    .D(_03_),
    .Q(ptr[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _63_ (
    .CLK(clk),
    .D(_04_),
    .Q(memory[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _64_ (
    .CLK(clk),
    .D(_05_),
    .Q(memory[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _65_ (
    .CLK(clk),
    .D(_06_),
    .Q(memory[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _66_ (
    .CLK(clk),
    .D(_07_),
    .Q(memory[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _67_ (
    .CLK(clk),
    .D(_08_),
    .Q(memory[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _68_ (
    .CLK(clk),
    .D(_09_),
    .Q(memory[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _69_ (
    .CLK(clk),
    .D(_10_),
    .Q(memory[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _70_ (
    .CLK(clk),
    .D(_11_),
    .Q(memory[7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _71_ (
    .CLK(clk),
    .D(_12_),
    .Q(dataOut),
    .RESET_B(rst)
  );
endmodule

module BAUD_RATE_GENERATOR(clk, rst, div, bclk);
  wire [11:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  output bclk;
  wire bclk;
  input clk;
  wire clk;
  wire [11:0] counter;
  input [11:0] div;
  wire [11:0] div;
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _053_ (
    .A(div[10]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor4_1 _054_ (
    .A(counter[8]),
    .B(counter[9]),
    .C(counter[10]),
    .D(counter[11]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor4_1 _055_ (
    .A(counter[4]),
    .B(counter[5]),
    .C(counter[6]),
    .D(counter[7]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor4b_1 _056_ (
    .A(counter[1]),
    .B(counter[2]),
    .C(counter[3]),
    .D_N(counter[0]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and3_1 _057_ (
    .A(_003_),
    .B(_004_),
    .C(_005_),
    .X(bclk)
  );
  sky130_fd_sc_hd__xnor2_1 _058_ (
    .A(div[1]),
    .B(counter[1]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__mux2i_1 _059_ (
    .A0(_006_),
    .A1(counter[0]),
    .S(div[0]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _060_ (
    .A(div[1]),
    .B(div[0]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor3_1 _061_ (
    .A(div[1]),
    .B(div[0]),
    .C(div[2]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor3_1 _062_ (
    .A(div[2]),
    .B(counter[2]),
    .C(_008_),
    .X(_010_)
  );
  sky130_fd_sc_hd__or4_1 _063_ (
    .A(div[1]),
    .B(div[0]),
    .C(div[2]),
    .D(div[3]),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor3_1 _064_ (
    .A(div[3]),
    .B(counter[3]),
    .C(_009_),
    .X(_012_)
  );
  sky130_fd_sc_hd__o2111ai_1 _065_ (
    .A1(counter[0]),
    .A2(_006_),
    .B1(_007_),
    .C1(_010_),
    .D1(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _066_ (
    .A(div[4]),
    .B(_011_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _067_ (
    .A(div[4]),
    .B(_011_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _068_ (
    .A(counter[4]),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor3_1 _069_ (
    .A(div[4]),
    .B(div[5]),
    .C(_011_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor3_1 _070_ (
    .A(div[5]),
    .B(counter[5]),
    .C(_014_),
    .X(_018_)
  );
  sky130_fd_sc_hd__or4_1 _071_ (
    .A(div[4]),
    .B(div[5]),
    .C(div[6]),
    .D(_011_),
    .X(_019_)
  );
  sky130_fd_sc_hd__xnor3_1 _072_ (
    .A(div[6]),
    .B(counter[6]),
    .C(_017_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and4b_1 _073_ (
    .A_N(_013_),
    .B(_016_),
    .C(_018_),
    .D(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _074_ (
    .A(div[7]),
    .B(_019_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _075_ (
    .A(div[7]),
    .B(_019_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _076_ (
    .A(counter[7]),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor3_1 _077_ (
    .A(div[8]),
    .B(div[7]),
    .C(_019_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__xnor3_1 _078_ (
    .A(div[8]),
    .B(counter[8]),
    .C(_022_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor4_1 _079_ (
    .A(div[8]),
    .B(div[7]),
    .C(div[9]),
    .D(_019_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor3_1 _080_ (
    .A(div[9]),
    .B(counter[9]),
    .C(_025_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and4_1 _081_ (
    .A(_021_),
    .B(_024_),
    .C(_026_),
    .D(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _082_ (
    .A(_002_),
    .B(_027_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _083_ (
    .A(_002_),
    .B(_027_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _084_ (
    .A(counter[10]),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xor3_1 _085_ (
    .A(div[11]),
    .B(counter[11]),
    .C(_030_),
    .X(_033_)
  );
  sky130_fd_sc_hd__a31oi_1 _086_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(counter[0]),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a31oi_1 _088_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_034_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nand2_1 _089_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _090_ (
    .A(counter[2]),
    .B(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__a31oi_1 _091_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_036_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__and4_1 _092_ (
    .A(counter[1]),
    .B(counter[2]),
    .C(counter[3]),
    .D(counter[0]),
    .X(_037_)
  );
  sky130_fd_sc_hd__a31oi_1 _093_ (
    .A1(counter[1]),
    .A2(counter[2]),
    .A3(counter[0]),
    .B1(counter[3]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a311oi_1 _094_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_037_),
    .C1(_038_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nand2_1 _095_ (
    .A(counter[4]),
    .B(_037_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xnor2_1 _096_ (
    .A(counter[4]),
    .B(_037_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a31oi_1 _097_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_040_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__xor2_1 _098_ (
    .A(counter[5]),
    .B(_039_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a31oi_1 _099_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_041_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__a31o_1 _100_ (
    .A1(counter[4]),
    .A2(counter[5]),
    .A3(_037_),
    .B1(counter[6]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand4_1 _101_ (
    .A(counter[4]),
    .B(counter[5]),
    .C(counter[6]),
    .D(_037_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a31oi_1 _103_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_044_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _104_ (
    .A(counter[7]),
    .SLEEP(_043_),
    .X(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _105_ (
    .A(counter[7]),
    .B(_043_),
    .X(_046_)
  );
  sky130_fd_sc_hd__a31oi_1 _106_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_046_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__nand2_1 _107_ (
    .A(counter[8]),
    .B(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _108_ (
    .A(counter[8]),
    .B(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a31oi_1 _109_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_048_),
    .Y(_000_[8])
  );
  sky130_fd_sc_hd__xor2_1 _110_ (
    .A(counter[9]),
    .B(_047_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a31oi_1 _111_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_049_),
    .Y(_000_[9])
  );
  sky130_fd_sc_hd__a31oi_1 _112_ (
    .A1(counter[8]),
    .A2(counter[9]),
    .A3(_045_),
    .B1(counter[10]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand4_1 _113_ (
    .A(counter[8]),
    .B(counter[9]),
    .C(counter[10]),
    .D(_045_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2b_1 _114_ (
    .A_N(_050_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a31oi_1 _115_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_052_),
    .Y(_000_[10])
  );
  sky130_fd_sc_hd__xor2_1 _116_ (
    .A(counter[11]),
    .B(_051_),
    .X(_001_)
  );
  sky130_fd_sc_hd__a31oi_1 _117_ (
    .A1(_029_),
    .A2(_032_),
    .A3(_033_),
    .B1(_001_),
    .Y(_000_[11])
  );
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(counter[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _119_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(counter[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(counter[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(counter[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(counter[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(counter[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(counter[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(counter[7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(counter[8]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(counter[9]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(counter[10]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(counter[11]),
    .RESET_B(rst)
  );
endmodule

module MUX(selector, start, data, parity, stop, idle, tx_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input data;
  wire data;
  input idle;
  wire idle;
  input parity;
  wire parity;
  input [2:0] selector;
  wire [2:0] selector;
  input start;
  wire start;
  input stop;
  wire stop;
  output tx_out;
  wire tx_out;
  sky130_fd_sc_hd__mux2i_1 _07_ (
    .A0(start),
    .A1(parity),
    .S(selector[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _08_ (
    .A(selector[1]),
    .B(data),
    .Y(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(_01_),
    .A1(_00_),
    .S(selector[0]),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _10_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor3b_1 _11_ (
    .A(selector[1]),
    .B(selector[0]),
    .C_N(selector[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__o21ai_0 _12_ (
    .A1(selector[2]),
    .A2(_03_),
    .B1(idle),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _13_ (
    .A(stop),
    .B(_04_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o221ai_1 _14_ (
    .A1(selector[2]),
    .A2(_02_),
    .B1(_04_),
    .B2(_05_),
    .C1(_06_),
    .Y(tx_out)
  );
endmodule

module RX_SYNC(clk, rst, rx_in, rx_out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input rx_in;
  wire rx_in;
  output rx_out;
  wire rx_out;
  wire sync_stage1;
  wire sync_stage2;
  sky130_fd_sc_hd__dfstp_2 _0_ (
    .CLK(clk),
    .D(rx_in),
    .Q(sync_stage1),
    .SET_B(rst)
  );
  sky130_fd_sc_hd__dfstp_2 _1_ (
    .CLK(clk),
    .D(sync_stage1),
    .Q(sync_stage2),
    .SET_B(rst)
  );
  assign rx_out = sync_stage2;
endmodule

module UART(clk, rst, parityEnable, parityType, tx_data_valid, tx_in, rx, div, rx_out, tx, parityError, parityErrorValid, tx_busy, rx_busy, rx_done, framingError, tx_done);
  wire bclk_wire;
  input clk;
  wire clk;
  input [11:0] div;
  wire [11:0] div;
  output framingError;
  wire framingError;
  input parityEnable;
  wire parityEnable;
  output parityError;
  wire parityError;
  output parityErrorValid;
  wire parityErrorValid;
  input parityType;
  wire parityType;
  input rst;
  wire rst;
  input rx;
  wire rx;
  output rx_busy;
  wire rx_busy;
  output rx_done;
  wire rx_done;
  output [7:0] rx_out;
  wire [7:0] rx_out;
  wire rx_sync;
  output tx;
  wire tx;
  output tx_busy;
  wire tx_busy;
  input tx_data_valid;
  wire tx_data_valid;
  output tx_done;
  wire tx_done;
  input [7:0] tx_in;
  wire [7:0] tx_in;
  BAUD_RATE_GENERATOR BRG (
    .bclk(bclk_wire),
    .clk(clk),
    .div(div),
    .rst(rst)
  );
  RX_SYNC rx_synchronizer (
    .clk(clk),
    .rst(rst),
    .rx_in(rx),
    .rx_out(rx_sync)
  );
  \$paramod$c5d5f6af8907815d9d88b76936d70ac1e6314167\RXTOP  rxtop (
    .bclk(bclk_wire),
    .busy(rx_busy),
    .clk(clk),
    .framingError(framingError),
    .pCheckError(parityError),
    .pCheckValid(parityErrorValid),
    .parEnable(parityEnable),
    .parityType(parityType),
    .rst(rst),
    .rx_done(rx_done),
    .rx_in(rx_sync),
    .rx_out(rx_out)
  );
  \$paramod$c5d5f6af8907815d9d88b76936d70ac1e6314167\TXTOP  txtop (
    .bclk(bclk_wire),
    .busy(tx_busy),
    .clk(clk),
    .dataInput(tx_in),
    .dataValid(tx_data_valid),
    .parEnable(parityEnable),
    .parityType(parityType),
    .rst(rst),
    .tx_done(tx_done),
    .tx_out(tx)
  );
endmodule
